# Generated by Django 3.2.16 on 2022-11-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('hardness', models.IntegerField()),
                ('solved_ratio', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=50)),
                ('user_email', models.TimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testCase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('testCase_in', models.TextField()),
                ('testCase_out', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='api.problem')),
            ],
        ),
    ]
