# Generated by Django 3.2.16 on 2022-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_problem_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblems',
            name='user_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userproblems',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
