# Generated by Django 3.2.16 on 2022-11-15 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221114_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_score', models.IntegerField()),
                ('last_date', models.DateField(auto_now_add=True)),
                ('user_code', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProblem', to='api.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProblem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
