# Generated by Django 3.2.16 on 2022-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221201_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblems',
            name='user_score',
            field=models.FloatField(default=0),
        ),
    ]
