# Generated by Django 3.2.16 on 2022-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userproblems_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='last_code',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='preset1',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='preset2',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='preset3',
        ),
        migrations.AddField(
            model_name='preset',
            name='code',
            field=models.TextField(default='def solution(n):\n\tanswer = 0\n\treturn answer'),
        ),
        migrations.AddField(
            model_name='preset',
            name='preset_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='complete_people',
            field=models.IntegerField(default=0),
        ),
    ]
