# Generated by Django 3.2.16 on 2022-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221201_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='reference',
            field=models.TextField(null=True),
        ),
    ]
